### ISSUE TITLE
Cannot install sage with nodefaults

### ISSUE THREAD

**Issue by saraedum** [conda-forge/sage-feedstock#27]
I am trying to create an `environment.yml` to build SageMath documentation on ReadTheDocs at https://github.com/MCLF/mclf/pull/107.

I thought it would be a good idea to take only packages from conda-forge and non from default so I wrote:
```
name: readthedocs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - sage=8.3
```

However, this makes `sage=8.3` unsatisfiable. Dropping the `nodefaults` line, pulls in these default packages
```
cairo                     1.14.12              h7636065_2
harfbuzz                  1.7.6                h5f0a787_1
libgcc-ng                 8.2.0                hdf63c60_1
libopenblas               0.3.3                h5a2b251_3
numpy                     1.15.4           py36h99e49ec_0
numpy-base                1.15.4           py36h2f8d375_0
qt                        5.6.2               h974d657_12  
```

It's probably not a big deal but still I am wondering why dependencies cannot be satisfied from conda-forge here? In particular I am not sure about mixing libopenblas from default and our packages.

I noted that already during the sage build some packages from default were used during testing but that's probably normal https://circleci.com/gh/conda-forge/sage-feedstock/118:
```
    cairo:                             1.14.12-h77bcde2_0                   defaults   
    glib:                              2.53.6-h5d9569c_2                    defaults   
    gmpy2:                             2.0.8-py36h10f8cd9_2                 defaults
    gstreamer:                         1.12.4-hb53b477_0                    defaults
    harfbuzz:                          1.7.6-hc5b324e_0                     defaults
    openjdk:                           8.0.152-h46b5887_1                   defaults
    qt:                                5.6.2-hd25b39d_14                    defaults
```

**Comment by saraedum** [comment]
@isuruf: Is this expected? Can I somehow debug what is causing these packages to be pulled?

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by isuruf** [comment]
Nope.
