### ISSUE TITLE
installing sage from conda-forge

### ISSUE THREAD

**Issue by DrWaleedAYousef** [conda-forge/sage-feedstock#29]
Issue:
unable to install sage; I created a new environment and then:

```
source activate MySageEnv
conda install -c conda-foge sage

```

it gives me several errors, e.g.,:

```
CondaVerificationError: The package for sympy located at /home/wyousef/Downloads/AAProgramsAA/anaconda3/pkgs/sympy-1.3-py27_1000
appears to be corrupted. The path 'lib/python2.7/site-packages/sympy/vector/tests/test_field_functions.pyc'
specified in the package manifest cannot be found.

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
```
</details>
     active environment : None
       user config file : /home/wyousef/.condarc
 populated config files : /home/wyousef/.condarc
          conda version : 4.6.4
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /home/wyousef/Downloads/AAProgramsAA/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/wyousef/Downloads/AAProgramsAA/anaconda3/pkgs
                          /home/wyousef/.conda/pkgs
       envs directories : /home/wyousef/Downloads/AAProgramsAA/anaconda3/envs
                          /home/wyousef/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/2.7.15 Linux/4.20.8-arch1-1-ARCH arch/ glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by saraedum** [comment]
A `CondaVerificationError` usually happens when the file could not be downloaded, probably because a connectivity issue. I just tried to download the `sympy-1.3-py27_1000` package manually and the file `lib/python2.7/site-packages/sympy/vector/tests/test_field_functions.pyc` is not missing.

I am not sure what's the proper way to download that package again. Probably you could just delete `/home/wyousef/Downloads/AAProgramsAA/anaconda3/pkgs/sympy-1.3-py27_1000` and the accompanying `tar.bz` file. But you might want to have a look at the conda documentation to find a better way.

**Comment by DrWaleedAYousef** [comment]
Moreover the file exists at that path which is the path of the base env

**Comment by DrWaleedAYousef** [comment]
I just tried installing miniconda and created a new environment for it and then from the new environment I did:
```
conda install -c conda-forge sage
```
it took forever to resolve the system and packages, and did not start installing!!

**Comment by saraedum** [comment]
Sorry, I don't understand. It's just hanging or did it return without installing anything? In any case, this feels like it's an issue with conda and not with the sage package itself. I know that the SAT solver that conda uses could take a very long time to resolve dependencies sometimes. I think that attempts such as https://github.com/conda/conda/issues/7694 tried to improve on that. Not sure if that would fix the particular issue that you are seeing though.

**Comment by saraedum** [comment]
Let me try to `conda install sage` here myself…

**Comment by saraedum** [comment]
I could imagine that the fact that we did not yet rebuild sage with the new conda compilers is causing unsatisfiable dependencies. @isuruf: Are you keeping track of which dependencies we are currently missing still?

**Comment by DrWaleedAYousef** [comment]
It's just hanging (i.e., keeping resolving dependencies). Did you manage to reproduce the problem?

**Comment by saraedum** [comment]
Yes, I can reproduce it. I just stopped it after it tried to resolve for two hours.
I'd recommend to report this on the conda package itself. They might have some ideas on what's the underlying problem.

**Comment by DrWaleedAYousef** [comment]
Is this related to the `sympy` problem above?

**Comment by dimpase** [comment]
> Yes, I can reproduce it. I just stopped it after it tried to resolve for two hours.

I'm trying to check the instructions on http://doc.sagemath.org/html/en/installation/conda.html

and it seems to hang on "Solving environment" - although it could just be the case that the SAT problem they are solving is pretty bad...

Did you have any progress on this?

**Comment by gschintgen** [comment]
Hi, installing sage via conda isn't working for me either (following the offical sagemath instructions on a fresh ubuntu-18.04 system). "Solving environment" hangs indefinitely. If I add `conda config --set channel_priority strict` it fails rather quickly with some error about unsatisfiable dependencies (can provide more details if needed.)

I then moved on to `conda search -f sage` and tried installing one or two older versions. No luck either.

Is there any known good version? Is there any specific debugging output that I could contribute?

**Comment by dimpase** [comment]
here are updated, working, instructions:
https://git.sagemath.org/sage.git/tree/src/doc/en/installation/conda.rst?id=af4b36bd9365a2b52de1849f47742ce7c59798dd

**Comment by dimpase** [comment]
feel free to review:
https://trac.sagemath.org/ticket/27950
(above update is the main part of this ticket)

**Comment by gschintgen** [comment]
> 
> 
> here are updated, working, instructions:
> https://git.sagemath.org/sage.git/tree/src/doc/en/installation/conda.rst?id=af4b36bd9365a2b52de1849f47742ce7c59798dd

Thanks! I'm currently trying them out. Unfortunately dependency resolution still seems to hang (>30 minutes), whereas the mamba alternative fails immediately with "Illegal instruction (core dumped)" (!?) This is on a Pentium Silver J5005 running Ubuntu-18.04 in a LXD container. I'll set up a fresh container - again. Just to make sure.

**Comment by dimpase** [comment]
try mamba, not conda.

**Comment by gschintgen** [comment]
I tried mamba on both a DIY-NAS and a VPS. It crashes immediately with "Illegal instruction (core dumped)".
VPS has a QEMU Virtual CPU, NAS the already mentioned J5005. So mamba is quite simply dysfunctional at this time.

(Do note that both times it's inside an LXD container, but given the many diverse systems I'm running that way without the slightest hickup I'm quite confident that the various conda-related issues I'm experiencing can't all be LXD-related. Unfortunately I can't try on a truly bare metal system.)

**Comment by dimpase** [comment]
On Fri, 14 Jun 2019 at 18:15, gschintgen <notifications@github.com> wrote:

> I tried mamba on both a DIY-NAS and a VPS. It crashes immediately with
> "Illegal instruction (core dumped)".
> VPS has a QEMU Virtual CPU, NAS the already mentioned J5005. So mamba is
> quite simply dysfunctional at this time.
>
> (Do note that both times it's inside an LXD container, but given the many
> diverse systems I'm running that way without the slightest hickup I'm quite
> confident that the various conda-related issues I'm experiencing can't all
> be LXD-related. Unfortunately I can't try on a truly bare metal system.)
>

I tried mamba/conda in a Crostini container (which is an LXD container)
running Debian, on a x86-64 (some i5 Intel CPU) Chromebook. It worked.

Perhaps your CPU is not usual. You may try asking mamba people.

**Comment by gschintgen** [comment]
On 14-Jun-19 20:08, Dima Pasechnik wrote:
> I tried mamba/conda in a Crostini container (which is an LXD container)
> running Debian, on a x86-64 (some i5 Intel CPU) Chromebook. It worked.
> 
> Perhaps your CPU is not usual. You may try asking mamba people.

Hmm, thanks for your input and confirming mamba is not completely 
broken. I supposed that at least my VPS had some a fully fledged modern 
CPU and that the available hardware features are forwarded to QEMU. As 
for the NAS, its Gemini Lake CPU is low power but quite recent. It turns 
out that currently mamba requires AVX2 and by "chance" both CPUs don't 
support it. Here's the relevant issue:
https://github.com/QuantStack/mamba/issues/33
Great.

This is getting out of hand for me. Initially I just wanted to set up 
sage in JupyterHub (actually "The littlest JupyterHub"), the resulting 
trouble led me to try sage with plain conda, and now mamba snobs my 
CPUs. At least I still got my old Sage/Jupyter/docker-in-LXD running and 
Ubuntu's version is working fine too.

If anything new comes up, I'll post it. Thanks again.

**Comment by isuruf** [comment]
You can now do `conda create -n sage sage=8.8.rc1` and conda should be able to solve the environment within a minute or two.

**Comment by dimpase** [comment]
Thanks. What are the platforms supported now?

(by the way, tried `mamba create -n sage sage=8.8.rc1` - it worked well too, I basically didn't see any delays for doing things - downloads took all the time)

**Comment by isuruf** [comment]
OS: linux-x86_64 and osx-x86_64
Python: 2.7,3.6,3.7

**Comment by DrWaleedAYousef** [comment]
Is archlinux supported?

**Comment by isuruf** [comment]
Yes, archlinux on x86_64 is supported.

**Comment by DrWaleedAYousef** [comment]
Do you mean this id a recent solution to the bug?

**Comment by isuruf** [comment]
Yes

**Comment by DrWaleedAYousef** [comment]
I tried it; it does not work.

**Comment by dimpase** [comment]
> I tried it; it does not work.

this certainly needs more info to be useful. Did you try a fresh conda install?

**Comment by DrWaleedAYousef** [comment]
I just tried the command you provided; and the message is:

------------
PackagesNotFoundError: The following packages are not available from current channels:

  - sage=8.8.rc1

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
------------

**Comment by dimpase** [comment]
I believe you need `-c conda-forge` option, as sage is only available on conda-forge channel.

**Comment by DrWaleedAYousef** [comment]
you mean:

conda create -n sage -c conda-forge sage=8.8.rc1

**Comment by dimpase** [comment]
our "canonical" instrictions are
```
conda config --add channels conda-forge
conda update --all
```
this will add `conda-forge` to your list of channels. Not sure whether `-c conda-forge` will be needed, too.

**Comment by saraedum** [comment]
You shouldn't need the `-c conda-forge` if you did `conda config --add channels conda-forge`.
The `conda update --all` is probably not necessary anymore. But it doesn't hurt either.

**Comment by DrWaleedAYousef** [comment]
After I added the channel and did:

conda create -n MySageEnv sage=8.8.rc1

it started downloading packages and then disconnected. Moreover, I did
not see any directory named "MySageEnv" under the env directory.

What seems to be working (still downloading packages now) with me is NOT
adding conda-forge as a channel and proceeding as follows

conda create -n MySageEnv
source activate MySageEnv
conda install -c conda-forge sage=8.8.rc1

As I said, it did not finish yet but it seems working.

**Comment by DrWaleedAYousef** [comment]
It finished successfully!

**Comment by saraedum** [comment]
For all practical purposes the two are identical. When connection errors happen, weird stuff happens I guess.

**Comment by saraedum** [comment]
Glad it worked after all :)

**Comment by DrWaleedAYousef** [comment]
One last question:

I used to use Sage from sage math. I had to install packaged for it.

How to do that in conda? How I install the whole sage packages?
