### ISSUE TITLE
sagemath 8.x does not install on fresh miniconda

### ISSUE THREAD

**Issue by csubich** [conda-forge/sage-feedstock#30]
Issue: Sagemath does not install on a fresh 'miniconda' distribution because of a package versioning issue

To reproduce:
Install fresh miniconda distribution (python 2.7)
Perform step 1 and 2 of https://doc.sagemath.org/html/en/installation/conda.html#sec-installation-conda (add conda-forge source, update)
Attempt to install the most recent sage by version (`conda create -v -n sage sage=8.3[build=py27_3]`)

Failure:
<code>
PackagesNotFoundError: The following packages are not available from current channels:

  - sage=8.3[build=py27_3] -> sagemath-db-conway-polynomials[version='>=0.5.*']
</code>

Specifically, the version number `0.5.p0` for `sagemath-db-conway-polynomials` does not appear to match the `>=0.5.*` specifier.

Conda version: `conda 4.6.8`

**Comment by csubich** [comment]
This error seems to date back at least to version 8.1 of the sage package for conda.  The version installed by the recommend `conda create -v -n sage sage` appears to be 7.6!

**Comment by csubich** [comment]
This may be related to change #7528 of conda, with version 4.6.0:

> bump minimum requests version to stable, unbundled release (#7528)

I think that conda interprets version 0.5.p0 of `sagemath-db-conway-polynomials` as a prerelease version, whereas the 'p' seems to instead stand for 'patchlevel'.

**Comment by isuruf** [comment]
For now, use `conda create -v -n sage sage -c conda-forge/label/cf201901`. the package here needs to be rebuilt.

**Comment by csubich** [comment]
Unfortunately, that workaround does not fix the issue:

    $ conda create -v -n sage sage=8.3 -c conda-forge/label/cf201901
    Collecting package metadata: ...working... done
    Solving environment: ...working... failed
    [...]
    PackagesNotFoundError: The following packages are not available from current channels:
    
      - sage=8.3 -> sagemath-db-conway-polynomials[version='>=0.5.*']

Leaving out the version seeks to install:

      sage               conda-forge/label/cf201901/linux-64::sage-7.6-py27_2

However, the install does work as expected after downgrading `conda` to version 4.5.12.

**Comment by isuruf** [comment]
Thanks. Can you send a PR to `sagemath-db-conway-polynomials-feedstock` to change the version from `0.5.p0` to `0.5.0` ?
