### ISSUE TITLE
Update to 8.8.rc1

### ISSUE THREAD

**Issue by isuruf** [conda-forge/sage-feedstock#33]
Changes to sagelib
- [ ] Remove cephes, libgap. Add gap, gmpy2, libbraiding, libhomfly, pplpy

Updates to packages
- [x] Update gmpy2 to the new beta. (https://github.com/conda-forge/gmpy2-feedstock/pull/14)
- [x] Package pplpy (https://github.com/conda-forge/staged-recipes/pull/8566)
- [x] Package libbraiding (https://github.com/conda-forge/staged-recipes/pull/8580)
- [x] Package libhomfly (https://github.com/conda-forge/staged-recipes/pull/8576)
- [x] Update gap to 4.10.1 (https://github.com/conda-forge/gap-feedstock/pull/16)
- [x] Update brial to 1.2.5 (https://github.com/conda-forge/brial-feedstock/pull/13)
- [x] Update cddlib to 0.94j
- [x] Update eclib to 20190226 (https://github.com/conda-forge/eclib-feedstock/pull/12)
- [x] Update giac to 1.5.0.37 (conda-forge/giac-feedstock#9)
- [x] Update gsl to 2.5 (conda-forge/gsl-feedstock#44)
- [x] Update giac for gsl 2.5
- [x] Update fflas-ffpack for gsl 2.5
- [x] Update cvxopt for gsl 2.5
- [x] Update maxima to 5.42.2 (https://github.com/conda-forge/maxima-feedstock/pull/16)
- [x] Update pari to 2.11.1 (https://github.com/conda-forge/pari-feedstock/pull/18)
- [x] Update lcalc for pari 2.11
- [x] Update giac for pari 2.11
- [x] Update eclib for pari 2.11
- [x] Update cypari2 for pari 2.11
- [x] Update cysignals for pari 2.11
- [x] Update pynac to 0.7.24 (https://github.com/conda-forge/pynac-feedstock/pull/15)
- [x] Update singular to 4.1.1 (https://github.com/conda-forge/singular-feedstock/pull/5)
- [x] Update pynac for singular 4.1.1
- [x] Update zn_poly to 0.9.1 (https://github.com/conda-forge/zn_poly-feedstock/pull/4)
- [x] Update eclib for ntl 11.3.2
- [x] Update linbox for ntl 11.3.2
- [x] Update flint for ntl 11.3.2
- [x] Update singular for ntl 11.3.2
- [ ] Update ecl for bdw-gc 8 (https://github.com/conda-forge/ecl-feedstock/pull/12)

Not sure whether these versions are needed
- [ ] Update igraph to 0.7.1999 
- [ ] Update python_igraph to 0.7.19999

Not important
- [ ] Update pkgconfig to 1.4.0
- [ ] Update gfan for singular 4.1.1

**Comment by Profpatsch** [comment]
zn_poly: done https://github.com/conda-forge/zn_poly-feedstock/pull/4

**Comment by Profpatsch** [comment]
singular: https://github.com/conda-forge/singular-feedstock/pull/5

Working on `igraph` and `python_igraph` next.

**Comment by slel** [comment]
gsl: https://github.com/conda-forge/gsl-feedstock/pull/44

**Comment by slel** [comment]
giac: https://github.com/conda-forge/giac-feedstock/pull/9

**Comment by Profpatsch** [comment]
igraph: https://github.com/conda-forge/igraph-feedstock/pull/10

**Comment by isuruf** [comment]
How to help with sagelib,

Install build tools

```
conda install conda-build conda-smithy
```

Clone my branch

```
git clone https://github.com/isuruf/sagelib-feedstock -b 8.8.rc1
cd sagelib-feedstock
```

Start a debug environment
```
conda debug recipe -m .ci_support/linux_python2.7.yaml
```

Run the command printed at the end which is something like
```
cd <path_to_debug_env>/work && source <path_to_debug_env>/work/build_env_setup.sh
```

Build
```
bash conda_build.sh
```
