### ISSUE TITLE
Update to 8.0

### ISSUE THREAD

**Issue by isuruf** [conda-forge/sage-feedstock#5]
8.0.beta3 is out, so it seems like we need to update a few packages.

- Update sagemath-db-conway-polynomials to 0.5
- Update cysignals to 1.6.3
- Update pari to 2.9.2

Also need to package cypari2

**Comment by isuruf** [comment]
@jdemeyer, would you be interested in creating a recipe for cypari2?

**Comment by jdemeyer** [comment]
> @jdemeyer, would you be interested in creating a recipe for cypari2?

To be honest, I never really used conda. So I guess the answer is "no". That being said, it's just a Python package, so `pip install` should do it.

**Comment by jdemeyer** [comment]
For cysignals, better use version 1.6.4, see https://trac.sagemath.org/ticket/22691

**Comment by isuruf** [comment]
Superceded by #10
