### ISSUE TITLE
Conda packages for SageMath with Python 3.8

### ISSUE THREAD

**Issue by nthiery** [conda-forge/sage-feedstock#59]
The latest jupyter/xxx-notebook images (e.g. used by binder) are based on Python 3.8.
This seems to be incompatible with the current conda packages:

```
docker run -ti --user root jupyter/minimal-notebook bash

(base) root@fae0b6c00255:~# conda install mamba -c conda-forge

(base) root@fae0b6c00255:~# mamba install sage
...
Encountered problems while solving.
Problem: nothing provides path.py >=7.1,<8 needed by sage-8.1-py27_1

(base) root@fae0b6c00255:~# mamba install sage=9.1
...
Encountered problems while solving.
Problem: package sage-9.1-py37hc8dfbb8_0 requires python >=3.7,<3.8.0a0, but none of the providers can be installed
```

**Comment by isuruf** [comment]
We'll have to wait till sage 9.2 to support python 3.8

**Comment by nthiery** [comment]
Oh, I see. I assumed that sage 9.0 already supported Python 3.8 because this is
the case with the Debian package on Ubuntu 20.04:
```
> sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.0, Release Date: 2020-01-01                     │
│ Using Python 3.8.2. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
```
I guess Debian is doing some patching to achieve this.

**Comment by nthiery** [comment]
Thanks for the feedback though!

**Comment by slel** [comment]
The good news is that Sage 9.2 will also support Python 3.9,
thanks to Sage Trac ticket 30184 merged in Sage 9.2.rc0.  : )

**Comment by slel** [comment]
Also discussed on sage-devel: https://groups.google.com/d/topic/sage-devel/d2a_0g1OlvE/discussion

**Comment by jeanmonet** [comment]
Hi - I understand 9.2 was [released yesterday](https://www.sagemath.org/changelogs/sage-9.2.txt). Any idea on when it will become available on `conda-forge`?
Also, I was wondering, seeing that `conda-forge` has no Windows version for this package, if there was a technical reason for it?

**Comment by isuruf** [comment]
You can follow the development at https://github.com/conda-forge/sagelib-feedstock/pull/105
As for windows, sage provides windows support only through cygwin (a linux emulation software) which we don't support at conda.

**Comment by jeanmonet** [comment]
Thank you for the info !

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/sage-feedstock/pull/60
