### ISSUE TITLE
Installation Failure on Windows 10 with Conda

### ISSUE THREAD

**Issue by ZakEspley** [conda-forge/sage-feedstock#85]
I was just following the [installation guide](https://doc.sagemath.org/html/en/installation/conda.html)

When I run
`conda create -n sage sage python=3.9 `
I get the following output:
```
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for sage:  75%|██████████████████████████████████████████████████████▊                  | 3/4 [00:15<00:05,  5.60s/it]|failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
python=3.9
sage -> python[version='>=3.6|>=3.7']
sage -> alabaster[version='>=0.7.12'] -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.5,<3.6.0a0|3.4.*|>=3.11,<3.12.0a0|>=3.5|>=3.8|>=2.7|>=3|>=3.3|>=3.6.1']The following specifications were found to be incompatible with your system:

  - feature:/win-64::__win==0=0
  - feature:|@/win-64::__win==0=0
  - sage -> ipykernel[version='>=6.6.0,<7'] -> __linux
  - sage -> ipykernel[version='>=6.6.0,<7'] -> __win

Your installed version is: 0
```

I have tried with Python 3.9, 3.10 and 3.11. I am not sure if I am missing something here.

**Comment by isuruf** [comment]
We don't support windows as sage itself doesn't support the msvc toolchain on windows.

**Comment by PaulKGrimes** [comment]
I have this same problem installing in a Rocky Linux 8 WSL installation, on Windows 10.  On Windows 11, the conda install just spins forever.  This is in a fresh miniconda environment on a fully updated Rocky Linux install.

`(sage) [pgrimes@ebirah RockyLinux-8]$ conda install sage
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.28=0
  - feature:/linux-64::__linux==5.15.90.1=0
  - feature:/linux-64::__unix==0=0
  - feature:|@/linux-64::__glibc==2.28=0
  - feature:|@/linux-64::__linux==5.15.90.1=0
  - feature:|@/linux-64::__unix==0=0
  - sage -> ipykernel[version='>=6.6.0,<7'] -> __linux
  - sage -> ipykernel[version='>=6.6.0,<7'] -> __osx
  - sage -> sympy[version='>=1.11.1,<2'] -> __unix

Your installed version is: 5.15.90.1

Note that strict channel priority may have removed packages required for satisfiability.`

**Comment by isuruf** [comment]
Please open a new issue with the required information in the issue template.
