### ISSUE TITLE
Update to SageMath 10.0

### ISSUE THREAD

**Issue by slel** [conda-forge/sage-feedstock#89]
SageMath 10.0 is out.

- announcement on the sage-release mailing list:
  -  https://groups.google.com/g/sage-release/c/BdHjadsnYUc
- SageMath 10.0 release at github:
  - https://github.com/sagemath/sage/releases/tag/10.0

**Comment by saraedum** [comment]
Packages in the SageMath distribution that have changed version between 9.8 and 10.0:

* [x] ~~argon2_cffi_bindings (new, 21.2.0)~~ (Jupyter dependency, not relevant here)
* [x] ~~cvxpy/package-version.txt (new, 1.3.0)~~ (optional)
* [x] ~~cylp (0.91.4 → 0.91.5)~~ (optional)
* [x] ~~e_antic (1.2.1 → 1.3.0)~~ (optional)
* [ ] eclib (20220621 → 20230424)
* [x] ~~ecos_python (new, 2.0.12)~~ (optional)
* [ ] gap (4.11.1 → 4.12.2)
* [ ] importlib_metadata (5.1.0 → 6.0.0)
* [ ] importlib_resources (5.10.0 → 5.12.0)
* [x] ~~libsemigroups (1.1.0 → 2.3.2)~~ (optional)
* [ ] meson (0.63.3 → 1.0.1)
* [ ] meson_python (0.11.0 → 0.12.1)
* [x] ~~msolve (0.4.4+sage-2022-09-11 → 0.4.9)~~ (optional)
* [x] ~~normaliz (3.9.4 → 3.10.0)~~ (optional)
* [x] ~~openssl (3.0.5 → 3.0.8)~~ (not relevant here)
* [x] ~~osqp_python (new, 0.6.2.post8)~~ (optional)
* [x] ~~polymake (4.7 → 4.9)~~ (optional)
* [ ] pplpy (0.8.6 → 0.8.7)
* [ ] primecount (7.4 → 7.6)
* [ ] primesieve (8.0 → 11.0)
* [x] ~~pynormaliz (2.17 → 2.18)~~ (optional)
* [x] ~~pyscipopt (4.2.0 → 4.3.0)~~ (optional)
* [ ] pythran (0.12.0 → 0.12.1)
* [x] ~~qdldl_python (new, 0.1.5.post3)~~ (optional)
* [ ] scipy (1.9.3 → 1.10.1)
* [x] ~~scs (new, 3.2.2)~~ (optional)
* [x] ~~singular (4.3.1p1 → 4.3.1p3)~~ (build script changes)
* [x] ~~sphinx_copybutton (new, 0.5.1)~~ (not relevant)
* [x] ~~typing_extensions (4.4.0 → 4.5.0)~~ (not relevant)
